"""empty message

Revision ID: 05eae4501f27
Revises: 391aae5aaadc
Create Date: 2022-05-31 09:08:15.398309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eae4501f27'
down_revision = '391aae5aaadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declare', sa.Column('localisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'declare', 'localisation', ['localisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'declare', type_='foreignkey')
    op.drop_column('declare', 'localisation_id')
    # ### end Alembic commands ###
