"""empty message

Revision ID: 08e4c6e2d63b
Revises: 05eae4501f27
Create Date: 2022-05-31 09:23:07.500367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08e4c6e2d63b'
down_revision = '05eae4501f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localisation', sa.Column('lng', sa.Float(), nullable=True))
    op.drop_column('localisation', 'long')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localisation', sa.Column('long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('localisation', 'lng')
    # ### end Alembic commands ###
