"""empty message

Revision ID: 215ea94f1036
Revises: 3f23d2ae16b5
Create Date: 2022-05-31 17:07:52.494169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215ea94f1036'
down_revision = '3f23d2ae16b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('declare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('localisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['localisation_id'], ['localisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('declare')
    op.drop_table('users')
    op.drop_table('localisation')
    # ### end Alembic commands ###
