"""empty message

Revision ID: 3f23d2ae16b5
Revises: 08e4c6e2d63b
Create Date: 2022-05-31 09:44:49.707889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f23d2ae16b5'
down_revision = '08e4c6e2d63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('declare', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('declare', 'type')
    # ### end Alembic commands ###
