"""empty message

Revision ID: 6d924a9bcd20
Revises: 9dd6ffa0adaa
Create Date: 2022-05-31 08:28:18.103543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d924a9bcd20'
down_revision = '9dd6ffa0adaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=70), nullable=True))
    op.add_column('users', sa.Column('passwordHash', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'model')
    op.drop_column('users', 'name')
    op.drop_column('users', 'doors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'passwordHash')
    op.drop_column('users', 'email')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###
